; PlatformIO Project Configuration
; ESP32 AI Thinker CAM

[env:esp32cam]
platform      = espressif32
board         = esp32cam
framework     = arduino

; Serial monitor speed
monitor_speed = 115200

; Upload speed (115200 = most stable for ESP32-CAM)
upload_speed  = 115200
upload_port   = COM14

; Prevent baud rate negotiation that causes packet corruption at end of flash
upload_flags  = --no-stub

; Partition scheme - needed for camera + OTA
board_build.partitions = huge_app.csv

; Required libraries
lib_deps =

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
